# Site settings
title: BMLT Days 2019
email: info@bmltdays.org
description: >- # this means to ignore newlines until "baseurl:"
  This site is dedicated to BMLT Days 2019 hosted by the Greater New York Region.
baseurl: ""
theme: jekyll-theme-cayman
exclude:
  - .idea
