# Site settings
title: BMLT Days
email: info@bmltdays.org
description: >- # this means to ignore newlines until "baseurl:"
  This site is dedicated to BMLT Days hosted by the Greater New York Region.
baseurl: ""
theme: jekyll-theme-slate
exclude:
  - .idea
