# Site settings
title: BMLT days
email: info@bmltdays.org
description: >- # this means to ignore newlines until "baseurl:"
  This site is dedicated to BMLT learning days.
baseurl: ""

# Build settings
theme: jekyll-theme-cayman